include: images/apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - coreutils
    - redis
    - redis-bitnami-compat
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 1001
  users:
    - username: nonroot
      uid: 1001
      gid: 1001
  run-as: nonroot

entrypoint:
  command: /bin/bash -c /opt/bitnami/scripts/redis/postunpack.sh && /opt/bitnami/scripts/redis/entrypoint.sh && /opt/bitnami/scripts/redis/run.sh

environment:
  BITNAMI_APP_NAME: redis

annotations:
  org.opencontainers.image.title: 'redis-server-bitnami'
  org.opencontainers.image.description: 'Redis-Server-Bitnami image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/redis-server-bitnami'
