contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - bash
    - bash-binsh
    - busybox
    - curl
    - ca-certificates-bundle
    - coreutils
    - glibc-locale-posix
    - jq
    - ncurses
    - wait-for-port
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: nonroot

paths:
  - path: /iamguarded
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0755
  - path: /iamguarded/minio
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0755
  - path: /iamguarded/minio/data
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0755
  - path: /data
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0755
  - path: /opt/iamguarded/minio/tmp
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0755

environment:
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

archs:
  - amd64
  - arm64

entrypoint:
  command: /opt/iamguarded/scripts/minio/entrypoint.sh

cmd: /opt/iamguarded/scripts/minio/run.sh

annotations:
  org.opencontainers.image.authors: 'GitGuardian SRE Team <sre@gitguardian.com>'
  org.opencontainers.image.description: 'MinIO-Iamguarded image based on Wolfi OS'
  org.opencontainers.image.licenses: 'MIT'
  org.opencontainers.image.source: 'https://github.com/GitGuardian/wolfi/tree/main/images/minio-bitnami'
  org.opencontainers.image.title: 'minio-iamguarded'
  org.opencontainers.image.vendor: 'GitGuardian'
