include: images/pgvector/prod.yaml

contents:
  packages:
    - pgvector-16
    - postgresql-16
    - postgresql-16-client
    - postgresql-16-oci-entrypoint-base=16.11-r0
    - postgresql-16-oci-entrypoint=16.11-r0
    - postgresql-16-contrib
