contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - bash
    - busybox
    - curl
    - ca-certificates-bundle
    - coreutils
    - glibc-locale-posix
    - jq
    - ncurses
    - readline
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 0
  run-as: nonroot

work-dir: /opt/bitnami/minio-client

archs:
  - amd64
  - arm64

entrypoint:
  command: /opt/bitnami/scripts/minio-client/entrypoint.sh

cmd: /opt/bitnami/scripts/minio-client/run.sh

environment:
  BITNAMI_APP_NAME: minio

annotations:
  org.opencontainers.image.authors: 'GitGuardian SRE Team <sre@gitguardian.com>'
  org.opencontainers.image.description: 'MinIO-Bitnami client image based on Wolfi OS'
  org.opencontainers.image.licenses: 'MIT'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/minio-bitnami-client'
  org.opencontainers.image.title: 'minio-bitnami-client'
  org.opencontainers.image.vendor: 'GitGuardian'
