include: images/ggshield/prod.yaml

contents:
  packages:
    - apk-tools
    - build-base
    - git
    - python-3.12-dev
    - py3.12-pip
    - uv
    - vim
    - wget
    - wolfi-keys

accounts:
  run-as: root
