include: images/apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - curl
    - ggshield
    - glibc-locale-posix
    - jq
    - wget
    - wolfi-baselayout
    - yq

entrypoint:
  command: /usr/sbin/ggshield

cmd: --help

annotations:
  org.opencontainers.image.title: 'ggshield'
  org.opencontainers.image.description: 'Scanner image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/ggshield'
