include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - coreutils
    - glibc-locale-posix
    - ncurses
    - wolfi-baselayout

entrypoint:
  command: /usr/bin/minio

annotations:
  org.opencontainers.image.title: 'minio'
  org.opencontainers.image.description: 'MinIO image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/minio'
