include: images/apko.yaml

contents:
  packages:
    - coreutils
    - busybox
    - curl

paths:
  - path: /mnt/data
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532
  - path: /.mc
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

entrypoint:
  command: /usr/bin/minio

cmd: server /mnt/data --console-address :9090 --address :9000

annotations:
  org.opencontainers.image.title: 'MinIO'
  org.opencontainers.image.description: 'MinIO image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/GitGuardian/wolfi/tree/main/images/minio'
