include: images/apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - icu-libs
    - postgresql
    - postgresql-bitnami-compat
    - postgresql-client
    - postgresql-contrib
    - postgresql-oci-entrypoint
    - su-exec
    - wolfi-baselayout

accounts:
  groups:
    - groupname: bitnami
      gid: 1001
  users:
    - username: bitnami
      uid: 1001
      gid: 1001
  run-as: bitnami

entrypoint:
  command: /opt/bitnami/scripts/postgresql/entrypoint.sh

cmd: /opt/bitnami/scripts/postgresql/run.sh

environment:
  BITNAMI_APP_NAME: postgresql
  LANG: en_US.UTF-8
  PGDATA: /opt/bitnami/postgresql/data

paths:
  - path: /opt/bitnami/postgresql/conf
    type: directory
    permissions: 0o770
    uid: 1001
    gid: 0
  - path: /opt/bitnami/postgresql/data
    type: directory
    permissions: 0o770
    uid: 1001
    gid: 0
  - path: /opt/bitnami/postgresql/logs
    type: directory
    permissions: 0o770
    uid: 1001
    gid: 0
  - path: /opt/bitnami/postgresql/tmp
    type: directory
    permissions: 0o770
    uid: 1001
    gid: 0

annotations:
  org.opencontainers.image.title: 'postgres-bitnami'
  org.opencontainers.image.description: 'Postgres-Bitnami image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/postgres-bitnami'
