include: images/apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - icu-libs
    - postgresql
    - postgresql-bitnami-compat
    - postgresql-client
    - postgresql-contrib
    - postgresql-oci-entrypoint
    - su-exec
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 1001
  users:
    - username: nonroot
      uid: 1001
      gid: 1001
  run-as: nonroot

entrypoint:
  command: /opt/bitnami/scripts/postgresql/entrypoint.sh

cmd: /opt/bitnami/scripts/postgresql/run.sh

environment:
  BITNAMI_APP_NAME: postgresql
  LANG: en_US.UTF-8
  PGDATA: /opt/bitnami/postgresql/data

annotations:
  org.opencontainers.image.title: 'postgres-bitnami'
  org.opencontainers.image.description: 'Postgres-Bitnami image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/postgres-bitnami'
