include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - bun
    - wolfi-baselayout

entrypoint:
  command: /usr/bin/bun

cmd: --help

annotations:
  org.opencontainers.image.title: 'bun'
  org.opencontainers.image.description: 'Bun image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/GitGuardian/wolfi/tree/main/images/bun'
