contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - bash
    - bash-binsh
    - busybox
    - ca-certificates-bundle
    - coreutils
    - glibc-locale-en
    - glibc-locale-posix
    - ncurses
    - gosu
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 0
  run-as: nonroot

work-dir: /opt/bitnami/redis

archs:
  - amd64
  - arm64

# https://hub.docker.com/r/bitnami/redis
environment:
  LANG: en_US.UTF-8
  BITNAMI_APP_NAME: "redis"
  BITNAMI_ROOT_DIR: "/opt/bitnami"
  REDIS_VOLUME_DIR: "/bitnami/redis"

  REDIS_DATA_DIR: "${REDIS_VOLUME_DIR}/data"
  REDIS_BASE_DIR: "${BITNAMI_ROOT_DIR}/redis"
  REDIS_CONF_DIR: "${REDIS_BASE_DIR}/etc"
  REDIS_DEFAULT_CONF_DIR: "${REDIS_BASE_DIR}/etc.default"
  REDIS_MOUNTED_CONF_DIR: "${REDIS_BASE_DIR}/mounted-etc"
  REDIS_CONF_FILE: "${REDIS_CONF_DIR}/redis.conf"
  REDIS_LOG_DIR: "${REDIS_BASE_DIR}/logs"
  REDIS_LOG_FILE: "${REDIS_LOG_DIR}/redis.log"
  REDIS_TMP_DIR: "${REDIS_BASE_DIR}/tmp"
  REDIS_PID_FILE: "${REDIS_TMP_DIR}/redis.pid"
  REDIS_BIN_DIR: "${REDIS_BASE_DIR}/bin"
  REDIS_OVERRIDES_FILE: "${REDIS_MOUNTED_CONF_DIR}/overrides.conf"

  REDIS_SENTINEL_PORT_NUMBER: "26379"
  REDIS_DEFAULT_PORT_NUMBER: "6379"
  REDIS_TLS_PORT_NUMBER: "6379"
  REDIS_PORT_NUMBER: ${REDIS_DEFAULT_PORT_NUMBER}
  REDIS_DAEMON_USER: "redis"
  REDIS_DAEMON_GROUP: "redis"
  REDIS_DATABASE: "redis"

  ALLOW_EMPTY_PASSWORD: "no"
  REDIS_AOF_ENABLED: "yes"
  REDIS_TLS_AUTH_CLIENTS: "yes"
  REDIS_TLS_ENABLED: "no"
  REDIS_ALLOW_REMOTE_CONNECTIONS: "yes"
  REDIS_RDB_POLICY_DISABLED: "no"

entrypoint:
  command: /opt/bitnami/scripts/redis/entrypoint.sh

cmd: /opt/bitnami/scripts/redis/run.sh

annotations:
  org.opencontainers.image.title: 'redis-bitnami'
  org.opencontainers.image.authors: 'GitGuardian SRE Team <sre@gitguardian.com>'
  org.opencontainers.image.description: 'Redis image with Bitnami compatibility based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/GitGuardian/wolfi/tree/main/images/redis-bitnami'
  org.opencontainers.image.licenses: 'MIT'
  org.opencontainers.image.vendor: 'GitGuardian'
