include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - dash
    - dash-binsh
    - glibc-locale-posix
    - wolfi-baselayout

entrypoint:
  command: /bin/sh -c 'exec java -cp "/tika-server-standard.jar:/tika-extras/*" org.apache.tika.server.core.TikaServerCli -h 0.0.0.0 $0 $@'

annotations:
  org.opencontainers.image.title: 'apache-tika'
  org.opencontainers.image.description: 'Apache-tika image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/apache-tika'
