include: images/python-gitguardian/shell.yaml

contents:
  packages:
    - apk-tools
    - build-base
    - git
    - ruff
    - uv
    - wolfi-keys
    # - py3-pip
    # - python3-dev

accounts:
  run-as: root
