include: images/python-gitguardian/shell.yaml

contents:
  packages:
    - apk-tools
    - build-base
    - docker-compose
    - git
    - postgresql-16-dev
    - ruff
    - uv~0.7
    - vim
    - wolfi-keys

accounts:
  run-as: root
