include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - cairo
    - curl
    - font-linux-libertine
    - font-noto-emoji
    - fontconfig-config
    - git
    - glibc-locale-posix
    - libgcrypt
    - libpq-16
    - pango
    - ripgrep
    - src-fingerprint
    - tini
    - wolfi-baselayout

paths:
  - path: /app
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532
  - path: /resources
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532
  - path: /cache
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532
  - path: /tmp/prometheus_multiproc_dir
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

entrypoint:
  command: /usr/bin/python

environment:
  PROMETHEUS_MULTIPROC_DIR: /tmp/prometheus_multiproc_dir

annotations:
  org.opencontainers.image.title: 'python-gitguadian'
  org.opencontainers.image.description: 'Python image based on Wolfi OS for GitGuardian'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/python-gitguardian'
