include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - ip6tables
    - iptables
    - libgcc
    - libmnl
    - libnetfilter_conntrack
    - libnfnetlink
    - libnftnl
    - wolfi-baselayout
    # - istio-envoy-1.25
    # - istio-envoy-1.25-compat
    # - istio-pilot-agent-25
    # - istio-pilot-agent-1.25-compat

entrypoint:
  command: /usr/local/bin/pilot-agent

annotations:
  org.opencontainers.image.title: 'istio-proxy'
  org.opencontainers.image.description: 'Istio-proxy image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/GitGuardian/wolfi/tree/main/images/istio-proxy'
