contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - bash
    - bash-binsh
    - busybox
    - ca-certificates-bundle
    - coreutils
    - glibc-locale-en
    - glibc-locale-posix
    - ncurses
    - gosu
    - icu-libs
    - libxslt
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 1001
  users:
    - username: nonroot
      uid: 1001
      gid: 0
  run-as: nonroot

work-dir: /opt/bitnami/postgresql

archs:
  - amd64
  - arm64

# https://hub.docker.com/r/bitnami/postgresql
environment:
  LANG: en_US.UTF-8
  PGDATA: "/bitnami/postgresql/data"
  BITNAMI_APP_NAME: "postgresql"
  BITNAMI_ROOT_DIR: "/opt/bitnami"

  POSTGRESQL_VOLUME_DIR: "/bitnami/postgresql"
  POSTGRESQL_DATA_DIR: "/bitnami/postgresql/data"
  POSTGRESQL_PORT_NUMBER: "5432"
  POSTGRESQL_ENABLE_LDAP: "no"
  POSTGRESQL_SHARED_PRELOAD_LIBRARIES: "pgaudit"
  POSTGRESQL_CLIENT_MIN_MESSAGES: "error"

entrypoint:
  command: /opt/bitnami/scripts/postgresql/entrypoint.sh

cmd: /opt/bitnami/scripts/postgresql/run.sh

annotations:
  org.opencontainers.image.title: 'pgvector-bitnami'
  org.opencontainers.image.authors: 'GitGuardian SRE Team <sre@gitguardian.com>'
  org.opencontainers.image.description: 'PGVector image with Bitnami compatibility based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/GitGuardian/wolfi/tree/main/images/pgvector-bitnami'
  org.opencontainers.image.licenses: 'MIT'
  org.opencontainers.image.vendor: 'GitGuardian'
