include: images/pgvector/prod.yaml

contents:
  packages:
    - pgvector-17
    - postgresql-17
    - postgresql-17-client
    - postgresql-16-oci-entrypoint-base
    - postgresql-17-oci-entrypoint
    - postgresql-17-contrib
