include: images/apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - glibc-locale-en
    - glibc-locale-posix
    - gosu
    - icu-libs
    - libxslt
    - wolfi-baselayout

accounts:
  groups:
    - groupname: postgres
      gid: 65532
  users:
    - username: postgres
      uid: 65532
      gid: 65532
  run-as: root

paths:
  - path: /var/lib/postgresql
    type: directory
    permissions: 0o770
    uid: 65532
    gid: 0
  - path: /var/lib/postgresql/data
    type: directory
    permissions: 0o770
    uid: 65532
    gid: 0
  - path: /var/run/postgresql
    type: directory
    permissions: 0o775
    uid: 65532
    gid: 0

work-dir: /home/postgres

environment:
  LANG: en_US.UTF-8
  PGDATA: /var/lib/postgresql/data

entrypoint:
  command: /usr/bin/docker-entrypoint.sh postgres

annotations:
  org.opencontainers.image.title: 'pgvector'
  org.opencontainers.image.description: 'PGVector image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/GitGuardian/wolfi/tree/main/images/pgvector'
