name: fluent-bit

on:
  schedule:
    - cron: "00 06 * * *"
  push:
    branches:
      - 'main'
    paths:
      - 'images/fluent-bit/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        include:
          - tag: latest
            target: prod
            packages: ''
          - tag: latest-shell
            target: shell
            packages: ''
          - tag: '3.2'
            target: prod
            packages: 'fluent-bit~3.2'
          - tag: '3.2-shell'
            target: shell
            packages: 'fluent-bit~3.2'
    name: ${{ matrix.tag }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.tag }}
      target: ${{ matrix.target }}
      packages: ${{ matrix.packages }}
    secrets: inherit
