name: ggshield

on:
  schedule:
    - cron: "00 01 * * 1-5"
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/ggshield.yaml
      - 'images/ggshield/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "1.38"]
        variant: [prod, dev]
        include:
          - version: latest
            packages: ''
          - version: "1.38"
            packages: 'ggshield~1.38'
    name: ${{ matrix.version }}${{ matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
      packages: ${{ matrix.packages }}
    secrets: inherit
