name: istio-proxy

on:
  schedule:
    - cron: "00 01 * * 1-5"
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/istio-proxy.yaml
      - 'images/istio-proxy/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "1.25", "1.25.2", "1.25.1"]
        variant: [prod, shell]
        include:
          - version: latest
            packages: 'istio-envoy-1.25,istio-envoy-1.25-compat,istio-pilot-agent-1.25,istio-pilot-agent-1.25-compat'
          - version: '1.25'
            packages: 'istio-envoy-1.25,istio-envoy-1.25-compat,istio-pilot-agent-1.25,istio-pilot-agent-1.25-compat'
          - version: '1.25.2'
            packages: 'istio-envoy-1.25~1.25.2,istio-envoy-1.25-compat~1.25.2,istio-pilot-agent-1.25~1.25.2,istio-pilot-agent-1.25-compat~1.25.2'
          - version: '1.25.1'
            packages: 'istio-envoy-1.25~1.25.1,istio-envoy-1.25-compat~1.25.1,istio-pilot-agent-1.25~1.25.1,istio-pilot-agent-1.25-compat~1.25.1'
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
      packages: ${{ matrix.packages }}
    secrets: inherit
