name: pgvector-bitnami

on:
  schedule:
    - cron: "00 01 * * 1-5"
  pull_request:
    paths:
      - .github/workflows/pgvector-bitnami.yaml
      - 'images/pgvector-bitnami/*.yaml'
      - 'images/pgvector-bitnami/**/*.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/pgvector-bitnami.yaml
      - 'images/pgvector-bitnami/*.yaml'
      - 'images/pgvector-bitnami/**/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "17"]
        variant: [prod]
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ format('{0}/{1}', matrix.version, matrix.variant) }}
    secrets: inherit
