name: pgvector

on:
  schedule:
    - cron: "00 01 * * 1-5"
  pull_request:
    paths:
      - .github/workflows/pgvector.yaml
      - 'images/pgvector/*.yaml'
      - 'images/pgvector/**/*.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/pgvector.yaml
      - 'images/pgvector/*.yaml'
      - 'images/pgvector/**/*.yaml'
  workflow_dispatch:

permissions:
  publish:
    strategy:
      matrix:
        version: [latest, "17"]
        variant: [prod, dev]
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ format('{0}/{1}', matrix.version, matrix.variant) }}
    secrets: inherit
